"""Seperate user name column into given and family

Revision ID: 210888fe1514
Revises: 82ba07db456d
Create Date: 2023-11-02 17:50:12.716775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210888fe1514'
down_revision: Union[str, None] = '82ba07db456d'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('given_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('family_name', sa.String(length=255), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'family_name')
    op.drop_column('user', 'given_name')
    # ### end Alembic commands ###
