"""User uniquifier must not be nullable

Revision ID: 1b270ba35f29
Revises: 128b05bdb34b
Create Date: 2023-10-05 18:23:18.055161

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b270ba35f29"
down_revision: Union[str, None] = "128b05bdb34b"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("fs_uniquifier", existing_type=sa.VARCHAR(length=64), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("fs_uniquifier", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###
