"""Create foreign keys

Revision ID: 4c34debb0abf
Revises: 1b270ba35f29
Create Date: 2023-10-09 08:11:15.121836

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c34debb0abf"
down_revision: Union[str, None] = "1b270ba35f29"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth2client") as batch_op:
        batch_op.drop_constraint("oauth2client", type_="foreignkey")
        batch_op.create_foreign_key(
            "oauth2client", "user", ["user_id"], ["fs_uniquifier"], ondelete="CASCADE"
        )
    with op.batch_alter_table("oauth2token") as batch_op:
        batch_op.drop_constraint("oauth2token", type_="foreignkey")
        batch_op.create_foreign_key(
            "oauth2token", "user", ["user_id"], ["fs_uniquifier"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key("oauth2token", "oauth2client", ["client_id"], ["client_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth2token") as batch_op:
        batch_op.drop_constraint("oauth2token", type_="foreignkey")
        batch_op.create_foreign_key("oauth2token", "user", ["user_id"], ["id"], ondelete="CASCADE")
    with op.batch_alter_table("oauth2client") as batch_op:
        batch_op.drop_constraint("oauth2client", type_="foreignkey")
        batch_op.create_foreign_key(
            "oauth2client", "user", ["user_id"], ["id"], ondelete="CASCADE"
        )
    # ### end Alembic commands ###
